language: node_js
node_js:
  - "4.2"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
install:
  - npm install
script:
  - npm test
